MCU_SERIES = MIMXRT1021
MCU_VARIANT = MIMXRT1021DAF5A

FROZEN_MANIFEST = $(BOARD_DIR)/manifest.py

MICROPY_FLOAT_IMPL = double
MICROPY_PY_MACHINE_SDCARD = 0
MICROPY_HW_FLASH_TYPE = qspi_nor_flash
MICROPY_HW_FLASH_SIZE = 0x800000  # 8MB

MICROPY_HW_SDRAM_AVAIL = 0
MICROPY_HW_SDRAM_SIZE  = 0x2000000  # 32MB

MICROPY_PY_LWIP = 0
MICROPY_PY_USSL = 0
MICROPY_SSL_MBEDTLS = 0
